version: "3.9"

services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./note-app-pl.key:/etc/nginx/conf.d/note-app-pl.key
      - ./note-app-pl.crt:/etc/nginx/conf.d/note-app-pl.crt
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - flask-app
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-app
    command: python -m gunicorn --bind 0.0.0.0:8000 --workers 4 "wsgi:app" --log-level debug
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network:
